# Generated by Django 3.1.2 on 2020-10-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201011_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='city',
            name='image_link',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
